config/routes.rb
DivvyUp::Application.routes.draw do
  get "sessions/new"
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  get '/signin',  to: 'sessions#new',         as: 'signin'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/howitworks', to: 'welcome#howitworks'

  root 'tours#index'

  resources :tours, only: [:index, :show] do
    resources :recommendations
  end

  resources :recommendations, only: [] do
    resources :votes, only: [:create]
  end

  resources :pois, only: [:show] do
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :poi
  belongs_to :user

  validates :text, presence: true, length: {in: 3..800}
  validates :user, presence: true
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  belongs_to :tour
  has_many :comments
  accepts_nested_attributes_for :comments
  validates :tour, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: {in: 5..2000}
  validates_presence_of :lat, :lng
  validates :image, presence: true
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :tour
  belongs_to :user
  has_many :votes
  
  validates :text, presence: true, length: {in: 3..800}
  validates :user, presence: true
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :pois
  has_many :recommendations
  has_many :comments, through: :pois
  validates :name, presence: true, length: {in: 2..20}
  validates_presence_of :lat, :lng
  validates :creator, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token


  has_many :tours, foreign_key: 'creator_id'
  has_many :comments
  has_many :recommendations
  has_many :votes 
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :username, presence: true, length: {in: 2...17}
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: {minimum: 6}
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :recommendation, dependent: :destroy
  belongs_to :user, dependent: :destroy 

  validates_presence_of :value 
  validates :user_id, :uniqueness => {:scope => [:recommendation_id]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :json, :xml, :html
  def create
    @poi = params[:poi_id]
    @comment = Comment.create(poi_id: @poi, user_id: current_user.id, text: strip_newlines)
    @curr_poi = Poi.find(@poi.to_i)
    comments = @curr_poi.comments.all
    # respond_with(@comment, location: '/pois/' + @poi + '/comments')
    respond_to do |format|
      format.js
    end
  end

  private
    def strip_newlines
      params[:comment][:text].gsub(/\n/," ").gsub(/\r/, "")
    end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  def show
    @poi = Poi.find(params[:id])
    @comment = Comment.new
    render 'show'
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def index
    @tour = Tour.find(params[:tour_id])
  end

  def create
    recommendation = Recommendation.new(recommendation_params)
    recommendation.user_id = current_user.id

    if recommendation.save
      redirect_to  "/tours/#{params[:tour_id]}/recommendations"
    end
  end

  private
  def recommendation_params
    params.require(:recommendation).permit(:text, :tour_id)
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash[:notice] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.all
    render 'index'
  end
  def show
    if Tour.find_by(id: params[:id])
      @tour = Tour.find(params[:id])
      @pois = @tour.pois
      render 'show'
    else
      render 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the DivvyUp!"
      sign_in @user
      redirect_to '/'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
  class VotesController < ApplicationController 
	  def create
		    @recommendation = Recommendation.find(params[:recommendation_id])
		    @vote = Vote.create(user_id: current_user.id, recommendation_id: @recommendation.id, value: 1) 
		    @sum = Vote.where(recommendation_id: @recommendation.id).sum("value")
		 	respond_to do |format|
		 		format.js
		 	end	    
	  end 	
	  private
	  def vote_params
	    params.require(:vote).permit(:user_id, :recommendation_id, :value)
	  end	 
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def howitworks

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article class="comment"><%= comment.text %><br><small><%= comment.user.username %> <%= comment.created_at %></small></article>

app/views/comments/_form.html.erb
<% if current_user %>
<%= form_for :comment, url: poi_comments_path(poi.id), id: "com_form#{poi.id}" , remote: true do |f| %>
  <p>
    <%= f.hidden_field :poi_id, {value: poi.id} %>
    <%= f.label :text, "Tell Us What You Think:" %>
    <br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit "Comment"%>
  </p>
<% end %>
<% else %>
	<p>Please <%=link_to "Sign In", signin_path %> or <%=link_to "Sign Up", signup_path %> to Comment</p>
<% end %>

app/views/comments/create.js.erb
$("#comments_container<%= @poi%>").append('<article class="comment"><%= @comment.text %><br><small><%= @comment.user.username %></small></article>')
$("#comments_container<%= @poi%> form").find('textarea').val('');

app/views/comments/temp_create.js.erb
page.insert_html :bottom, 'comments_container<%=@poi%>', partial: 'comments/comment', object: comment

app/views/pois/_form.html.erb
<% if current_user %>
  <%= form_for(poi.comments.new) do |f| %>
    <p><%= f.label :text, "Leave comment:" %><br>
      <%= f.text_area :text %>
    </p>
    <p><%= f.submit "Comment"%></p>
  <% end %>
<% else %>
  <%= link_to 'signin-able', signin %> or <%= link_to 'signup', signup %>

app/views/pois/_show.html.erb
<article>
<img src='/assets/trump_tower.jpg' height='42' width='42'>
<h1>Trump Tower</h1>
<%= poi.name %><br>
<%= poi.location %><br>
<%= poi.description %><br>
<%= render partial: 'comments/comment', locals:{poi: poi}%>
</article>

app/views/pois/_slide.html.erb
<% @pois.each do |poi| %>
<li class="slider__item">
  <div class="map_div_placeholder">
    <div class="map_placeholder">

    </div>
  </div>
  <div class="elem">
    <h1><%= poi.name %></h1>
    <p><%= poi.description %></p>
    <div id="comment_container">
      <%= escape_javascript(render partial: "comments/form", locals:{poi: poi}) %>
      <%= render partial: "comments/comment", locals:{poi: poi}%>
    </div>
  </div>
</li>
<% end %>

app/views/recommendations/index.html.erb
<div class="form_container">
<h3>Recommended Stops for the <%= @tour.name %></h3>
<a href=# onclick="go_to(<%=@tour.id%>)">Back</a>

<% if current_user %>
  <%= form_for(:recommendation, url: "/tours/#{@tour.id}/recommendations") do |f| %>
      <br>
      <div class="row">
      <div class="small-9 columns">
        <%= f.hidden_field :tour_id, {value: @tour.id} %>
        <%= f.label :text, "What stop do you think we should add:" %>
        <%= f.text_area :text %>
      </div>
    </div>
    <div class="row">
      <div class="small-9 columns">
        <%= f.submit "Submit", class: "button tiny [radius round]" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row">
    <article class="recommendation">
      To make a recommendation <%= link_to 'signin', signin_path %> or <%= link_to 'signup', signup_path %>.
    </article>
  </div>
<% end %>

<% if @tour.recommendations.any? %>
  <div class="row">
    <% @tour.recommendations.each do |r| %>
      <article class="comment">
        <%= raw(r.text.gsub(/\n+/, "<br/>")) %><br>
        <small><%= r.user.username %> <%= r.created_at %></small>
        <% if current_user %>
     <small ><%= link_to image_tag("thumbs_up.png"), recommendation_votes_path(r), remote: true, method: :post, class: "thumbs_up", id: "rec_#{r.id}" %> </small>
        <% else %>
        <small>Please <%= link_to 'signin', signin_path %> or <%= link_to 'signup', signup_path %> to vote</small>
        <% end %>
        <small> + <span id="vote_<%=r.id%>"> <%= Vote.where(recommendation_id: r.id).sum("value")%> </span> </small>
      </article>
    <% end %>
  </div>
<% end %>

</div>
<script type="text/javascript">
  function go_to(page) {
    window.open('/tours/' + page, "_self");
  }
</script>

app/views/tours/_slide.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<li class="slider__item" style="background-image: url(<%= asset_path('architecture_tour_slide.jpg') %>); background-repeat: no-repeat; background-); background-repeat: no-repeat; background-size: cover;">
  <div class="map_div_placeholder">
    <div class="map_placeholder"></div>
  </div>

  <div class="elem">
    <h1><%= @tour.name %></h1>

    <%= link_to "Recommend Stops", tour_recommendations_path(@tour), class:"recom" %>
    <br>
    <br>
    <p>
      <input type="button" value="Show my nearest Divvy!" class="my_divvy" />
      <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
    </p>

    <p><%= @tour.long_description %></p>
  </div>
</li>

<% @pois.each do |poi| %>
<li class="slider__item" style="background-image: url(<%= asset_path(poi.image) %>); background-repeat: no-repeat; background-);
    background-repeat: no-repeat; background-size: cover;">
  <div class="map_div_placeholder">
    <div class="map_placeholder">

    </div>
  </div>
  <div id="elem<%=poi.id%>" class="elem">
    <h1><%= poi.name %></h1>
    <p>
      <input type="button" value="Show my nearest Divvy!" class="my_divvy" />
      <input type="button" value="Back to Tour Description" class="tour_desc" />
    </p>
    <p><%= poi.description %></p>
      <div id="comments_container<%= poi.id %>">
      <%= render partial: "comments/form", locals:{poi: poi} %>
      <%= render partial: "comments/comment", collection: poi.comments%>
      </div>
  </div>
</li>
<% end %>
 <!-- /assets/architecture_tour_slide.jpg -->

app/views/tours/index.html.erb
<div class="vid">
  <div id="title">
  <h1 style="font-family: 'Audiowide', cursive;"><img src= "<%= asset_path('logo.svg') %>" width="50%" height="50%"/>Up Tours</h1>
  </div>
  <div class="sub_title">
    Combine the adventure of a Divvy bike ride
    with the sights of Chicago. We have a selection of self-guided bike
    tours you are bound to enjoy.
  </div>

  <div class="intro">

    <ul class="tour_list">
    <% Tour.all.each do |tour| %>
      <li><h4><a href=# onclick="go_to(<%=tour.id%>)"><%= tour.name %></a></h4></li>
      <p><%= tour.short_description %></p>
    <% end %>
    </ul>
  </div>
</div>


<%= javascript_include_tag 'jquery.vide.min'%>
<script type="text/javascript">

  function go_to(page) {
    window.open('/tours/' + page, "_self");
  }

  $(function(){
    $('.vid').ready(function(){
      $('.vid').vide("<%= asset_path('bike.mp4') %>",{playbackRate: 1, 
        muted: true,
        loop: true,
        autoplay: true});
    });
  });
</script>

 <!-- "/assets/logo.svg" -->
 <!-- may need to host the video on amazon -->
 

app/views/tours/show.html.erb
<%= javascript_include_tag 'jquery.glide' %>

<%= javascript_include_tag 'tour_map' %>
<script type="text/javascript">
  $(function(){
    $('.slider__wrapper').html('<%= escape_javascript(render partial:"slide" ) %>');
    $('.slider').glide({
        arrows: false,
        autoplay: false,
        navigation: 'body',
        circular: false
        });
  });
</script>
  <div class="map_div">
    <div id="map"></div>
  </div>
  <div class="slider">
    <ul class="slider__wrapper">

    </ul>
  </div>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_signin.html.erb
<%= form_for(:session, url: sessions_path) do |t| %>
	<div id="error_explanation">
	 <%= flash[:notice] %>
	</div>
  
  <div class="row">
    <div class="small-6 columns">
      <%= t.label :email %> 
      <%= t.email_field :email %>
    </div>
  </div>

  <div class="row">
    <div class="small-6 columns">
      <%= t.label :enter_password %> 
      <%= t.password_field :password %>
    </div>
  </div>

  <div class="row">
    <div class="small-6 columns">
      <%= t.submit value="Sign in", class: "button tiny [radius round]" %>
    </div>
  </div>
<% end %>

app/views/users/_signup.html.erb
<%= form_for(@user) do |t| %>
  <%= render 'error_messages' %>
    <div class="row">
      <div class="small-6 columns">
          <%= t.label :email %>
          <%= t.email_field :email %>
        </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
          <%= t.label :username %>
          <%= t.text_field :username %>
        </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
          <%= t.label :enter_password %>
          <%= t.password_field :password %>
        </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
          <%= t.label :password_confirmation %>
          <%= t.password_field :password_confirmation %>
        </div>
      </div>

    <div class="row">
      <div class="small-6 columns">
        <%= t.submit value="Sign up", class: "button tiny [radius round]" %>
      </div>
    </div>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'signup' %>

app/views/votes/create.js.erb
$('span#vote_<%=@recommendation.id %>').text(<%=@sum%>);

app/views/welcome/howitworks.html.erb
<%= javascript_include_tag 'jquery.glide' %>
<script type="text/javascript">
  $(function(){
    $('.slider').glide({
        arrows: 'body',
        autoplay: false,
        navigation: 'body',
        circular: false
        });
  });
</script>

<div class="slider">
  <ul class="slider__wrapper">
      <li class="slider__item">
        <div class="presentation">
          <h1>Team Divvy Up</h1>
          <br><br><br>
          <h3>Overview</h3>
          <br><br>
          <h3>Work Flow</h3>
        </div>
      </li>

      <li class="slider__item">
        <div class="presentation">
          <h1>Process</h1>
          <h3>MVP</h3>
          <ul>
            <li>Tour Guide</li>
          </ul>
          <h3>User Feedback</h3>
          <ul>
            <li>Intuitive UI</li>
            <li>Visibility</li>
          </ul>
          <h3>Technology Insights</h3>
          <ul>
            <li>Geolocation</li>
            <li>Divvy API</li>
            <li>Rails</li>
          </ul>
        </div>
      </li>
      <li class="slider__item">
        <div class="presentation">
          <h1>General Intentions</h1>
          <h3>Design</h3>
          <ul>
            <li>Benchmark</li>
            <li>Color Scheme</li>
            <li>Vide.js</li>
            <li>Glide.js</li>
          </ul>
          <br>
          <h3>Difficulties</h3>
          <ul>
            <li>jQuery</li>
            <li>GMaps.js</li>
            <li>Asynchronous Loading</li>
          </ul>
        </div>
      </li>
      <li class="slider__item">
        <div class="presentation">
          <h1>Questions?</li>
        </div>
      </li>
  </ul>
</div>

app/views/welcome/index.html.erb
<div id="intro"><h2> Divvy Up </h2>
<button class="round">Get Started</button>
</div>

<div id="carousel">
<img src="../../assets/images/Night-Chicago.jpg" alt="Night Chicago">
</div>

<%= link_to "Sign Up", signup_path %>

<%= link_to "Log In", signup_path %>
    <%= flash[:success] %>

  <ul>
    <li> Architectural Tour </li>
    <li> Party Tour </li>
    <li> On the Run Tour </li>
    <li> Crime and Mob Tour </li>
    <li> Prohibition Tour </li>
    <li> Film Tour </li>
    <li> City Sights Tour </li>
    <li> Grand Tour </li>
  </ul>

<iframe src="//player.vimeo.com/video/52302939" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="http://vimeo.com/52302939">Cityscape Chicago</a>