config/routes.rb
DivvyUp::Application.routes.draw do
  get "sessions/new"
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  get '/signin',  to: 'sessions#new',         as: 'signin'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/howitworks', to: 'welcome#howitworks'

  root 'tours#index'

  resources :tours, only: [:index, :show] do
    resources :recommendations
  end

  resources :recommendations, only: [] do
    resources :votes, only: [:create]
  end

  resources :pois, only: [:show] do
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :poi
  belongs_to :user

  validates :text, presence: true, length: {in: 3..800}
  validates :user, presence: true
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  belongs_to :tour
  has_many :comments
  accepts_nested_attributes_for :comments
  validates :tour, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: {in: 5..2000}
  validates_presence_of :lat, :lng
  validates :image, presence: true
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :tour
  belongs_to :user
  has_many :votes
  
  validates :text, presence: true, length: {in: 3..800}
  validates :user, presence: true
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :pois
  has_many :recommendations
  has_many :comments, through: :pois
  validates :name, presence: true, length: {in: 2..20}
  validates_presence_of :lat, :lng
  validates :creator, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token


  has_many :tours, foreign_key: 'creator_id'
  has_many :comments
  has_many :recommendations
  has_many :votes 
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :username, presence: true, length: {in: 2...17}
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: {minimum: 6}
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :recommendation, dependent: :destroy
  belongs_to :user, dependent: :destroy 

  validates_presence_of :value 
  validates :user_id, :uniqueness => {:scope => [:recommendation_id]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :json, :xml, :html
  def create
    @poi = params[:poi_id]
    @comment = Comment.create(poi_id: @poi, user_id: current_user.id, text: strip_newlines)
    @curr_poi = Poi.find(@poi.to_i)
    comments = @curr_poi.comments.all
    # respond_with(@comment, location: '/pois/' + @poi + '/comments')
    respond_to do |format|
      format.js
    end
  end

  private
    def strip_newlines
      params[:comment][:text].gsub(/\n/," ").gsub(/\r/, "")
    end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  def show
    @poi = Poi.find(params[:id])
    @comment = Comment.new
    render 'show'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash[:notice] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.all
    render 'index'
  end
  def show
    if Tour.find_by(id: params[:id])
      @tour = Tour.find(params[:id])
      @pois = @tour.pois
      render 'show'
    else
      render 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the DivvyUp!"
      sign_in @user
      redirect_to '/'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
  class VotesController < ApplicationController 
	  def create
		    @recommendation = Recommendation.find(params[:recommendation_id])
		    @vote = Vote.create(user_id: current_user.id, recommendation_id: @recommendation.id, value: 1) 
		    @sum = Vote.where(recommendation_id: @recommendation.id).sum("value")
		 	respond_to do |format|
		 		format.js
		 	end	    
	  end 	
	  private
	  def vote_params
	    params.require(:vote).permit(:user_id, :recommendation_id, :value)
	  end	 
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def howitworks

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title>Divvy Up</title>

    <link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= stylesheet_link_tag "foundation-icons" %>
    <%= csrf_meta_tags %>

  </head>




  <body>
    <%= render 'partials/nav' %>


    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
    <nav class="top-bar" data-topbar data-options="is_hover: false">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/" style="font-family: 'Audiowide', cursive;"><img src="<%= asset_path('logo.svg') %>" width="50%" height="50%"/> Up Tours</a></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><span>Menu</span></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-dropdown">
          <a href="#">Tour</a>
            <ul class="dropdown">
              <% Tour.all.each do |tour| %>
                <li><a href='/tours/<%=tour.id%>'><%= tour.name %></a></li>
              <% end %>
            </ul>
        </li>
        <li class="item"><%= link_to "About", howitworks_path, method: "get" %></li>
      </ul>

      <!-- Right Nav Section -->
      <ul class="right">
        <% if signed_in? %>
          <li>
            <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign in', signin_path %>
          </li>
          <li>
            <%= link_to 'Sign up', signup_path %>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>